# 7th class - February 13th {-}

1. Something new I learned in class within the past 24 hours: 

Today's class was great for better understanding Data model, Process model, and Parameter model on a hierarchical framework. In addition to that, it is now clearer how can we add assumptions to our model, choosing distributions for each layer of the hierarchical model that reflects our real data. What is the support of the expected value and observed value was also something new from today's class, in my opinion, it is a very important step, and we should spend some time at the beginning of our data analysis process to consider unique information regarding our data which will help later when selecting the most appropriate distribution.


2. Something I am struggling to understand that was covered in class within the past 24 hours:

Something I am struggling to understand is the dynamic mathematical model example covered in class, well I could get the idea behind the dependence on births, deaths, and growth rate in the very beginning, and how it is was written, but from there to get the analytical solution, is something that is not that clear in my head at this point.
